services:
  - type: web
    name: contactos-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: contactos-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: contactos-db
          property: password
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false

databases:
  - name: contactos-db
    databaseName: contactos
    user: contactos_user
    plan: free